name: Say Hello

on:
  push:
    branches:
      - feature_08

jobs:
  hello_word:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the messaje
        run:
          echo "Hola mundo!!!"
      - name: Dime la fecha
        run:
          date
      - name: Mostrar contenido
        run:
          ls -l